#! /bin/sh

sxhkd &

bspc monitor HDMI-0 I II

bspc config border_width         8
bspc config window_gap          12
bspc config focused_border_color "#6f1f0a"
bspc config normal_border_color "#1d1e27"
bspc config active_border_color "#4A3788"
bspc presel_feedback_color "#2B5846"

bspc config external_rules_command "~/.config/bspwm/bspwm_rules"
bspc config split_ratio          0.60
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Pavucontrol desktop='^1' state=floating rectangle=700x500+15+2035
bspc rule -a Blueman-manager state=floating rectangle=600x400+440+80 desktop='^1'
bspc rule -a GLava desktop='^1' manage=off
bspc rule -a rofi focus=on follow=on
bspc rule -a Screenkey manage=off
bspc rule -a firefox state=floating rectangle=900x1600
bspc rule -a Brave-browser state=floating
bspc rule -a Alacritty state=floating
bspc rule -a Spotify state=floating
bspc rule -a code state=floating
bspc rule -a keepasscx state=floating


/usr/lib/kdeconnectd &
~/.config/polybar/launch.sh &
compton -f &
xbindkeys &
feh --bg-scale DP-0 ~/Downloads/wallpaper/spore_mod_2.jpg --bg-scale HDMI-0 ~/Downloads/wallpaper/spore_mod_3.jpg --bg-scale DVI-D-1 ~/Downloads/wallpaper/spore_mod_3.jpg

