#!/bin/sh

border= \
center= \
class=$2 \
desktop= \
focus= \
follow= \
hidden= \
id=${1?} \
instance=$3 \
layer= \
locked= \
manage= \
marked= \
misc=$4 \
monitor= \
node= \
private= \
rectangle= \
split_dir= \
split_ratio= \
state= \
sticky= \
urgent=;

spotify() {
	desktop=^1;
  state=floating;
}


case $instance.$class in
	(*.Chromium) chromium;;
	(*.Emacs) emacs;;
	(*.Gimp) gimp;;
	(*.Gitk) gitk;;
	(*.Pidgin) pidgin;;
	(*.Pinentry-gtk-2) pinentry_gtk_2;;
	(*.Signal) signal;;
	(*.Spotify) spotify;;
	(*.TelegramDesktop) telegram_desktop;;
	(*.XCalc) xcalc;;
	(*.Xmessage) xmessage;;
	(*.[Ff]irefox) firefox;;
	(*.mpv) mpv;;
	(*org.remmina.Remmina) remmina;;
	([lL]ibre[oO]ffice*) libreoffice;;
	(jetbrains-idea.jetbrains-idea) jetbrains_idea;;
	(stj*.st) stj1;;
	(weechatw.*) weechat;;
	(.)
		case $(ps -p "$(xdo pid "$id")" -o comm= 2>/dev/null) in
			(spotify) spotify;;
		esac;;
esac;

pri
case $instance.$class in
	(*.Chromium) chromium;;
	(*.Emacs) emacs;;
	(*.Gimp) gimp;;
	(*.Gitk) gitk;;
	(*.Pidgin) pidgin;;
	(*.Pinentry-gtk-2) pinentry_gtk_2;;
	(*.Signal) signal;;
	(*.Spotify) spotify;;
	(*.TelegramDesktop) telegram_desktop;;
	(*.XCalc) xcalc;;
	(*.Xmessage) xmessage;;
	(*.[Ff]irefox) firefox;;
	(*.mpv) mpv;;
	(*org.remmina.Remmina) remmina;;
	([lL]ibre[oO]ffice*) libreoffice;;
	(jetbrains-idea.jetbrains-idea) jetbrains_idea;;
	(stj*.st) stj1;;
	(weechatw.*) weechat;;
	(.)
		case $(ps -p "$(xdo pid "$id")" -o comm= 2>/dev/null) in
			(spotify) spotify;;
		esac;;
esac;

printf \
	${border:+"border=$border"} \
	${center:+"center=$center"} \
	${desktop:+"desktop=$desktop"} \
	${focus:+"focus=$focus"} \
	${follow:+"follow=$follow"} \
	${hidden:+"hidden=$hidden"} \
	${layer:+"layer=$layer"} \
	${locked:+"locked=$locked"} \
	${manage:+"manage=$manage"} \
	${marked:+"marked=$marked"} \
	${monitor:+"monitor=$monitor"} \
	${node:+"node=$node"} \
	${private:+"private=$private"} \
	${rectangle:+"rectangle=$rectangle"} \
	${split_dir:+"split_dir=$split_dir"} \
	${split_ratio:+"split_ratio=$split_ratio"} \
	${state:+"state=$state"} \
	${sticky:+"sticky=$sticky"} \
	${urgent:+"urgent=$urgent"};ntf \
	${border:+"border=$border"} \
	${center:+"center=$center"} \
	${desktop:+"desktop=$desktop"} \
	${focus:+"focus=$focus"} \
	${follow:+"follow=$follow"} \
	${hidden:+"hidden=$hidden"} \
	${layer:+"layer=$layer"} \
	${locked:+"locked=$locked"} \
	${manage:+"manage=$manage"} \
	${marked:+"marked=$marked"} \
	${monitor:+"monitor=$monitor"} \
	${node:+"node=$node"} \
	${private:+"private=$private"} \
	${rectangle:+"rectangle=$rectangle"} \
	${split_dir:+"split_dir=$split_dir"} \
	${split_ratio:+"split_ratio=$split_ratio"} \
	${state:+"state=$state"} \
	${sticky:+"sticky=$sticky"} \
	${urgent:+"urgent=$urgent"};
