#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
tint2 &
dropbox &

bspc monitor -d I II III IV

bspc config border_width 3
bspc config window_gap 12
bspc config active_border_color "#22483D"

bspc rule -a Alacritty state=floating rectangle=900x800+675+700
bspc rule -a firefox state=floating rectangle=1800x1400+10+50


feh --bg-scale ~/Downloads/thingy.jpg