#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x picom > /dev/null || picom &
pgrep -x tint2 > /dev/null || tint2 &
#tint2 ~/.config/tint2/unleashed/unleashed-taskbar.tint2rc &
#tint2 ~/.config/tint2/unleashed/unleashed-statusbar.tint2rc &
#tint2 ~/.config/tint2/unleashed/unleashed-workspace.tint2rc &
#tint2 ~/.config/tint2/unleashed/unleashed-clock.tint2rc &
#tint2 ~/.config/tint2/unleashed/unleashed-bookmark.tint2rc &


dropbox &

bspc monitor -d I II III IV

bspc config border_width 3
bspc config window_gap 12
bspc config active_border_color "#22483D"

bspc rule -a Alacritty state=floating rectangle=900x800+675+700
bspc rule -a firefox state=floating rectangle=1800x1400+10+50


feh --bg-scale ~/Downloads/thingy.jpg