#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
tint2 &
dropbox &

bspc monitor -d I II III IV

bspc config border_width 4
bspc config window_gap 12
bspc config active_border_color "#22483D"
bspc config border_radius 15

bspc rule -a Alacritty state=floating rectangle=900x800+675+700
bspc rule -a firefox state=floating
bspc rule -a code state=floating rectangle=1200x1400+10+800


feh --bg-scale ~/Downloads/thingy.jpg