#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
tint2 &
dropbox &

bspc monitor -d I II III IV

bspc config border_width 4
bspc config window_gap 12
bspc config active_border_color "#22483D"
bspc config border_radius 15

bspc rule -a Alacritty state=floating rectangle=900x800+675+700
bspc rule -a Firefox state=floating rectangle=1600x1200
bspc rule -a Code state=floating


feh --bg-scale ~/Downloads/thingy.jpg